In [8]:
uforeport <- read.csv("ufo.csv", na.strings = c("", " ", "NA"))
View(uforeport)

titanic <- read.csv("titanic.csv", na.strings = c("", " ", "NA"))
View(titanic)

      City                 Colors.Reported Shape.Reported State
1     Ithaca               NA              TRIANGLE       NY
2     Willingboro          NA              OTHER          NJ
3     Holyoke              NA              OVAL           CO
4     Abilene              NA              DISK           KS
5     New York Worlds Fair NA              LIGHT          NY
6     Valley City          NA              DISK           ND
7     Crater Lake          NA              CIRCLE         CA
8     Alma                 NA              DISK           MI
9     Eklutna              NA              CIGAR          AK
10    Hubbard              NA              CYLINDER       OR
11    Fontana              NA              LIGHT          CA
12    Waterloo             NA              FIREBALL       AL
13    Belton               RED             SPHERE         SC
14    Keokuk               NA              OVAL           IA
15    Ludington            NA              DISK           MI
16    Forest Home          NA              CIRCLE         CA
17    Los Angeles          NA              NA             CA
18    Hapeville            NA              NA             GA
19    Oneida               NA              RECTANGLE      TN
20    Bering Sea           RED             OTHER          AK
21    Nebraska             NA              DISK           NE
22    NA                   NA              NA             LA
23    NA                   NA              LIGHT          LA
24    Owensboro            NA              RECTANGLE      KY
25    Wilderness           NA              DISK           WV
26    San Diego            NA              CIGAR          CA
27    Wilderness           NA              DISK           WV
28    Clovis               NA              DISK           NM
29    Los Alamos           NA              DISK           NM
30    Ft. Duschene         NA              DISK           UT
⋮     ⋮                    ⋮               ⋮              ⋮
18212 Holyoke              NA              DIAMOND        MA
18213 Carson               NA              DISK           CA
18214 Pasadena             GREEN           FIREBALL       CA
18215 Austin               NA              FORMATION      TX
18216 El Campo             NA              OTHER          TX
18217 Garden Grove         ORANGE          LIGHT          CA
18218 Berthoud Pass        NA              TRIANGLE       CO
18219 Sisterdale           NA              DIAMOND        TX
18220 Garden Grove         NA              CHEVRON        CA
18221 Shasta Lake          BLUE            DISK           CA
18222 Franklin             NA              DISK           NH
18223 Albrightsville       NA              OTHER          PA
18224 Greenville           NA              NA             SC
18225 Eufaula              NA              DISK           OK
18226 Simi Valley          NA              FORMATION      CA
18227 San Francisco        NA              FORMATION      CA
18228 San Francisco        NA              TRIANGLE       CA
18229 Kingsville           NA              LIGHT          TX
18230 Chicago              NA              DISK           IL
18231 Pismo Beach          NA              OVAL           CA
18232 Pismo Beach          NA              OVAL           CA
18233 Lodi                 NA              NA             WI
18234 Anchorage            RED             VARIOUS        AK
18235 Capitola             NA              TRIANGLE       CA
18236 Fountain Hills       NA              NA             AZ
18237 Grant Park           NA              TRIANGLE       IL
18238 Spirit Lake          NA              DISK           IA
18239 Eagle River          NA              NA             WI
18240 Eagle River          RED             LIGHT          WI
18241 Ybor                 NA              OVAL           FL
      Time
1     6/1/1930 22:00
2     6/30/1930 20:00
3     2/15/1931 14:00
4     6/1/1931 13:00
5     4/18/1933 19:00
6     9/15/1934 15:30
7     6/15/1935 0:00
8     7/15/1936 0:00
9     10/15/1936 17:00
10    6/15/1937 0:00
11    8/15/1937 21:00
12    6/1/1939 20:00
13    6/30/1939 20:00
14    7/7/1939 2:00
15    6/1/1941 13:00
16    7/2/1941 11:30
17    2/25/1942 0:00
18    6/1/1942 22:30
19    7/15/1942 1:00
20    4/30/1943 23:00
21    6/1/1943 15:00
22    8/15/1943 0:00
23    8/15/1943 0:00
24    10/15/1943 11:00
25    1/1/1944 10:00
26    1/1/1944 12:00
27    1/1/1944 12:00
28    4/2/1944 11:00
29    6/1/1944 12:00
30    6/30/1944 10:00
⋮     ⋮
18212 12/28/2000 18:00
18213 12/28/2000 18:20
18214 12/28/2000 19:10
18215 12/29/2000 0:00
18216 12/29/2000 9:00
18217 12/29/2000 16:10
18218 12/29/2000 19:30
18219 12/29/2000 20:00
18220 12/29/2000 20:30
18221 12/29/2000 20:30
18222 12/29/2000 20:50
18223 12/29/2000 21:00
18224 12/29/2000 22:00
18225 12/29/2000 23:30
18226 12/30/2000 10:00
18227 12/30/2000 22:00
18228 12/30/2000 22:00
18229 12/31/2000 4:00
18230 12/31/2000 11:45
18231 12/31/2000 20:00
18232 12/31/2000 20:00
18233 12/31/2000 20:30
18234 12/31/2000 21:00
18235 12/31/2000 22:00
18236 12/31/2000 23:00
18237 12/31/2000 23:00
18238 12/31/2000 23:00
18239 12/31/2000 23:45
18240 12/31/2000 23:45
18241 12/31/2000 23:59

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
⋮   ⋮           ⋮        ⋮
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
⋮   ⋮                                                         ⋮      ⋮   ⋮
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked
1   0     A/5 21171          7.2500 NA          S
2   0     PC 17599          71.2833 C85         C
3   0     STON/O2. 3101282   7.9250 NA          S
4   0     113803            53.1000 C123        S
5   0     373450             8.0500 NA          S
6   0     330877             8.4583 NA          Q
7   0     17463             51.8625 E46         S
8   1     349909            21.0750 NA          S
9   2     347742            11.1333 NA          S
10  0     237736            30.0708 NA          C
11  1     PP 9549           16.7000 G6          S
12  0     113783            26.5500 C103        S
13  0     A/5. 2151          8.0500 NA          S
14  5     347082            31.2750 NA          S
15  0     350406             7.8542 NA          S
16  0     248706            16.0000 NA          S
17  1     382652            29.1250 NA          Q
18  0     244373            13.0000 NA          S
19  0     345763            18.0000 NA          S
20  0     2649               7.2250 NA          C
21  0     239865            26.0000 NA          S
22  0     248698            13.0000 D56         S
23  0     330923             8.0292 NA          Q
24  0     113788            35.5000 A6          S
25  1     349909            21.0750 NA          S
26  5     347077            31.3875 NA          S
27  0     2631               7.2250 NA          C
28  2     19950            263.0000 C23 C25 C27 S
29  0     330959             7.8792 NA          Q
30  0     349216             7.8958 NA          S
⋮   ⋮     ⋮                ⋮        ⋮           ⋮
862 0     28134            11.5000  NA          S
863 0     17466            25.9292  D17         S
864 2     CA. 2343         69.5500  NA          S
865 0     233866           13.0000  NA          S
866 0     236852           13.0000  NA          S
867 0     SC/PARIS 2149    13.8583  NA          C
868 0     PC 17590         50.4958  A24         S
869 0     345777            9.5000  NA          S
870 1     347742           11.1333  NA          S
871 0     349248            7.8958  NA          S
872 1     11751            52.5542  D35         S
873 0     695               5.0000  B51 B53 B55 S
874 0     345765            9.0000  NA          S
875 0     P/PP 3381        24.0000  NA          C
876 0     2667              7.2250  NA          C
877 0     7534              9.8458  NA          S
878 0     349212            7.8958  NA          S
879 0     349217            7.8958  NA          S
880 1     11767            83.1583  C50         C
881 1     230433           26.0000  NA          S
882 0     349257            7.8958  NA          S
883 0     7552             10.5167  NA          S
884 0     C.A./SOTON 34068 10.5000  NA          S
885 0     SOTON/OQ 392076   7.0500  NA          S
886 5     382652           29.1250  NA          Q
887 0     211536           13.0000  NA          S
888 0     112053           30.0000  B42         S
889 2     W./C. 6607       23.4500  NA          S
890 0     111369           30.0000  C148        C
891 0     370376            7.7500  NA          Q

In [15]:
# To count the total NA values
cat("total NA values ufo: ", sum(is.na(uforeport)),"\n")
cat("total NA values titanic: ", sum(is.na(titanic)),"\n")
# To get the positions where NA values are
cat("ufo: ")
which(is.na(uforeport))
cat("titanic: ")
which(is.na(titanic))
# To see how it work in smaller dataset, run code below
cat(" ")
demo = c(1, 2, NA, 4, NA, 6, 7)
sum(is.na(demo))
which(is.na(demo))
# Get count of NA in each column
cat( "  ")
print(sapply(uforeport, function(x) sum(is.na(x))))
cat( "  ")
print(sapply(titanic, function(x) sum(is.na(x))))

total NA values ufo:  18028
total NA values titanic:  866
ufo:

    [1]    22    23   205   242   614  1878  2014  2547  3124  4737  5270  6736
   [13]  7209  8829  8968  9274  9389  9588 10400 11626 12442 15768 15813 16055
   [25] 16609 18242 18243 18244 18245 18246 18247 18248 18249 18250 18251 18252
   [37] 18253 18255 18256 18257 18258 18259 18260 18262 18263 18264 18265 18266
   [49] 18267 18268 18269 18270 18271 18272 18273 18274 18275 18276 18277 18279
   [61] 18280 18281 18282 18283 18284 18285 18287 18288 18289 18290 18291 18292
   [73] 18293 18294 18295 18296 18297 18298 18299 18300 18301 18302 18303 18304
   [85] 18305 18306 18307 18309 18310 18311 18312 18313 18314 18315 18316 18317
   [97] 18318 18319 18320 18321 18322 18323 18325 18327 18328 18329 18330 18331
  [109] 18332 18334 18335 18336 18337 18338 18339 18340 18341 18342 18343 18344
  [121] 18345 18346 18347 18348 18349 18350 18351 18352 18354 18355 18356 18357
  [133] 18358 18359 18360 18361 18363 18364 18365 18366 18367 18368 18369 18370
  [145] 18372 18373 18374 18375 18376 18377 18378 18379 18381 18382 18383 18384
  [157] 18385 18386 18387 18388 18389 18390 18391 18392 18393 18395 18396 18397
  [169] 18398 18400 18401 18402 18403 18404 18407 18408 18409 18410 18411 18412
  [181] 18413 18414 18415 18417 18418 18419 18421 18422 18423 18424 18425 18426
  [193] 18427 18428 18429 18430 18431 18432 18433 18434 18435 18436 18437 18438
  [205] 18439 18440 18441 18442 18443 18445 18446 18447 18448 18449 18450 18451
  [217] 18452 18453 18454 18455 18456 18457 18458 18459 18460 18461 18462 18463
  [229] 18464 18465 18466 18467 18469 18470 18472 18473 18474 18475 18476 18477
  [241] 18478 18479 18481 18482 18484 18485 18486 18487 18488 18489 18490 18492
  [253] 18493 18494 18495 18496 18497 18499 18500 18501 18502 18503 18504 18505
  [265] 18506 18507 18508 18509 18510 18511 18512 18513 18514 18515 18516 18517
  [277] 18518 18519 18520 18521 18522 18523 18524 18525 18526 18527 18528 18529
  [289] 18532 18533 18534 18535 18536 18537 18538 18539 18540 18541 18542 18543
  [301] 18544 18545 18547 18548 18549 18550 18551 18552 18554 18555 18557 18558
  [313] 18559 18560 18561 18562 18563 18564 18566 18567 18568 18569 18570 18571
  [325] 18572 18573 18574 18575 18576 18577 18578 18579 18580 18581 18582 18583
  [337] 18584 18585 18587 18588 18589 18590 18591 18592 18593 18594 18595 18597
  [349] 18598 18599 18600 18601 18602 18603 18604 18606 18607 18608 18609 18610
  [361] 18611 18612 18613 18614 18615 18616 18617 18618 18619 18620 18621 18622
  [373] 18624 18626 18627 18628 18629 18630 18632 18633 18634 18635 18636 18637
  [385] 18638 18639 18640 18641 18642 18643 18644 18645 18646 18647 18648 18649
  [397] 18650 18651 18652 18653 18654 18655 18656 18657 18658 18659 18661 18662
  [409] 18663 18664 18665 18666 18667 18668 18669 18670 18671 18672 18673 18674
  [421] 18675 18677 18678 18679 18680 18681 18682 18683 18684 18685 18686 18687
  [433] 18688 18689 18690 18691 18692 18693 18694 18695 18696 18697 18698 18699
  [445] 18700 18701 18702 18703 18704 18705 18706 18707 18708 18709 18710 18711
  [457] 18712 18713 18714 18715 18716 18717 18718 18719 18720 18721 18722 18723
  [469] 18724 18725 18726 18727 18728 18729 18730 18731 18732 18733 18734 18735
  [481] 18736 18737 18738 18739 18740 18741 18742 18743 18744 18745 18746 18747
  [493] 18748 18749 18750 18751 18752 18753 18754 18756 18757 18758 18759 18760
  [505] 18761 18762 18763 18764 18765 18766 18767 18768 18769 18770 18772 18773
  [517] 18774 18775 18776 18777 18778 18779 18780 18781 18782 18783 18784 18785
  [529] 18786 18787 18788 18789 18790 18791 18792 18793 18794 18795 18796 18797
  [541] 18798 18799 18800 18801 18802 18803 18804 18805 18806 18807 18808 18809
  [553] 18810 18811 18812 18813 18814 18815 18817 18818 18819 18820 18821 18822
  [565] 18823 18824 18825 18826 18827 18828 18829 18830 18831 18832 18834 18835
  [577] 18836 18837 18838 18839 18840 18841 18842 18843 18844 18845 18846 18847
  [589] 18848 18849 18850 18851 18852 18853 18854 18855 18856 18857 18858 18859
  [601] 18861 18862 18863 18864 18865 18866 18867 18868 18869 18870 18871 18873
  [613] 18874 18875 18876 18877 18878 18879 18880 18882 18883 18884 18885 18886
  [625] 18887 18888 18889 18890 18891 18892 18894 18895 18896 18897 18898 18899
  [637] 18900 18901 18902 18903 18905 18906 18907 18908 18909 18910 18912 18913
  [649] 18914 18915 18916 18917 18918 18919 18920 18921 18922 18924 18925 18926
  [661] 18927 18928 18929 18930 18931 18932 18933 18934 18936 18937 18938 18939
  [673] 18940 18941 18942 18943 18944 18947 18948 18950 18951 18952 18953 18954
  [685] 18955 18956 18957 18958 18959 18960 18961 18962 18963 18964 18965 18966
  [697] 18967 18968 18969 18970 18971 18972 18973 18974 18975 18976 18977 18979
  [709] 18981 18982 18983 18984 18985 18986 18987 18988 18989 18991 18992 18993
  [721] 18994 18995 18996 18997 18998 18999 19001 19002 19003 19004 19005 19006
  [733] 19007 19008 19009 19010 19011 19012 19013 19014 19015 19016 19017 19018
  [745] 19019 19020 19021 19023 19024 19025 19026 19027 19028 19029 19030 19031
  [757] 19033 19034 19035 19036 19037 19039 19040 19041 19042 19043 19044 19045
  [769] 19046 19047 19048 19049 19050 19051 19052 19053 19054 19055 19056 19057
  [781] 19058 19059 19060 19061 19062 19063 19064 19066 19068 19069 19070 19071
  [793] 19072 19073 19074 19075 19076 19077 19078 19079 19080 19081 19082 19083
  [805] 19084 19085 19086 19087 19089 19090 19091 19092 19093 19094 19095 19096
  [817] 19097 19098 19099 19100 19101 19102 19103 19104 19105 19106 19107 19108
  [829] 19109 19110 19111 19112 19113 19114 19115 19116 19117 19119 19120 19123
  [841] 19124 19125 19126 19127 19128 19129 19131 19132 19133 19134 19135 19137
  [853] 19138 19139 19140 19141 19143 19144 19145 19146 19147 19148 19149 19151
  [865] 19152 19153 19154 19155 19156 19157 19158 19159 19160 19161 19162 19163
  [877] 19164 19165 19166 19167 19168 19169 19170 19171 19172 19173 19174 19175
  [889] 19176 19177 19178 19179 19180 19181 19182 19183 19184 19185 19186 19187
  [901] 19188 19189 19190 19191 19192 19193 19194 19195 19196 19197 19198 19199
  [913] 19200 19201 19202 19203 19205 19206 19207 19208 19209 19210 19211 19212
  [925] 19213 19214 19215 19216 19217 19218 19219 19220 19221 19222 19223 19224
  [937] 19225 19227 19228 19229 19230 19231 19232 19233 19234 19235 19236 19237
  [949] 19238 19239 19240 19241 19242 19243 19244 19245 19246 19247 19248 19249
  [961] 19250 19251 19252 19253 19254 19255 19256 19257 19259 19261 19262 19263
  [973] 19264 19265 19266 19268 19269 19270 19271 19272 19274 19275 19276 19277
  [985] 19278 19279 19280 19281 19282 19283 19284 19285 19288 19289 19291 19292
  [997] 19293 19295 19296 19298 19299 19300 19301 19302 19304 19305 19306 19307
 [1009] 19308 19309 19310 19311 19312 19313 19314 19315 19316 19317 19318 19319
 [1021] 19320 19321 19322 19323 19324 19325 19326 19327 19328 19330 19332 19334
 [1033] 19335 19336 19337 19339 19340 19341 19342 19343 19345 19346 19348 19349
 [1045] 19351 19352 19353 19354 19356 19358 19359 19360 19361 19362 19363 19364
 [1057] 19365 19366 19367 19368 19369 19371 19373 19376 19377 19379 19380 19381
 [1069] 19382 19383 19384 19385 19386 19387 19388 19389 19390 19391 19392 19393
 [1081] 19394 19395 19396 19397 19398 19399 19401 19402 19403 19404 19405 19406
 [1093] 19407 19408 19409 19410 19411 19412 19413 19415 19417 19418 19419 19420
 [1105] 19421 19422 19423 19424 19426 19427 19428 19429 19430 19431 19432 19433
 [1117] 19434 19435 19436 19437 19438 19439 19440 19441 19442 19443 19444 19445
 [1129] 19446 19447 19448 19449 19450 19451 19452 19453 19454 19455 19456 19457
 [1141] 19458 19459 19460 19461 19462 19463 19464 19465 19466 19469 19470 19471
 [1153] 19472 19473 19474 19475 19476 19477 19478 19479 19480 19481 19482 19483
 [1165] 19484 19485 19486 19487 19488 19489 19490 19491 19492 19493 19494 19495
 [1177] 19496 19497 19499 19500 19501 19502 19503 19504 19505 19506 19507 19508
 [1189] 19510 19511 19512 19513 19514 19515 19516 19517 19518 19519 19520 19521
 [1201] 19522 19524 19525 19526 19527 19528 19529 19530 19531 19532 19533 19535
 [1213] 19536 19537 19538 19539 19540 19541 19544 19545 19546 19547 19549 19550
 [1225] 19552 19553 19554 19555 19557 19558 19559 19560 19561 19562 19563 19564
 [1237] 19565 19566 19567 19568 19569 19570 19572 19573 19574 19576 19577 19578
 [1249] 19579 19580 19581 19583 19584 19585 19587 19588 19590 19591 19593 19594
 [1261] 19595 19596 19597 19598 19599 19600 19601 19602 19603 19604 19605 19606
 [1273] 19607 19608 19609 19610 19611 19612 19614 19615 19616 19617 19618 19619
 [1285] 19620 19621 19622 19623 19624 19625 19626 19627 19628 19629 19630 19631
 [1297] 19633 19634 19635 19636 19637 19638 19639 19640 19641 19642 19643 19644
 [1309] 19645 19646 19647 19648 19649 19650 19651 19652 19653 19654 19655 19656
 [1321] 19657 19658 19659 19660 19661 19662 19663 19664 19666 19667 19668 19669
 [1333] 19670 19671 19672 19673 19674 19675 19677 19678 19679 19680 19681 19682
 [1345] 19683 19684 19685 19686 19687 19688 19690 19691 19692 19693 19694 19695
 [1357] 19696 19697 19698 19699 19700 19701 19702 19703 19704 19705 19706 19707
 [1369] 19708 19709 19710 19712 19713 19714 19715 19716 19717 19719 19720 19721
 [1381] 19722 19723 19724 19725 19726 19727 19728 19729 19730 19731 19732 19733
 [1393] 19735 19736 19737 19738 19739 19740 19741 19742 19743 19744 19745 19746
 [1405] 19747 19748 19749 19750 19751 19752 19753 19755 19756 19757 19758 19759
 [1417] 19760 19761 19762 19763 19765 19766 19767 19768 19769 19770 19771 19772
 [1429] 19773 19774 19775 19776 19777 19778 19780 19781 19782 19783 19784 19786
 [1441] 19788 19789 19790 19791 19792 19793 19795 19796 19798 19799 19800 19801
 [1453] 19802 19804 19805 19806 19807 19808 19809 19810 19811 19812 19813 19814
 [1465] 19815 19816 19817 19818 19819 19820 19821 19822 19823 19824 19825 19827
 [1477] 19828 19830 19831 19832 19833 19834 19836 19837 19838 19840 19841 19842
 [1489] 19843 19844 19845 19846 19847 19849 19850 19851 19852 19853 19854 19855
 [1501] 19856 19857 19858 19859 19860 19861 19862 19864 19865 19866 19867 19868
 [1513] 19869 19870 19871 19872 19873 19874 19875 19876 19878 19879 19880 19881
 [1525] 19882 19883 19884 19885 19886 19887 19888 19889 19890 19891 19893 19894
 [1537] 19896 19897 19898 19899 19901 19902 19903 19904 19906 19907 19908 19909
 [1549] 19910 19911 19912 19913 19914 19915 19916 19917 19918 19919 19920 19921
 [1561] 19922 19923 19924 19925 19926 19927 19929 19931 19932 19933 19934 19935
 [1573] 19936 19937 19938 19939 19940 19941 19942 19943 19944 19945 19946 19947
 [1585] 19949 19951 19952 19953 19954 19955 19956 19957 19958 19959 19960 19961
 [1597] 19963 19964 19965 19966 19968 19969 19970 19971 19972 19973 19974 19975
 [1609] 19976 19978 19979 19980 19983 19984 19985 19986 19987 19988 19989 19990
 [1621] 19991 19992 19993 19994 19995 19996 19997 19998 20000 20001 20002 20003
 [1633] 20004 20005 20006 20007 20008 20009 20010 20011 20012 20013 20014 20015
 [1645] 20016 20017 20018 20020 20021 20022 20023 20024 20025 20026 20027 20028
 [1657] 20029 20030 20031 20032 20033 20034 20036 20038 20039 20040 20041 20042
 [1669] 20043 20044 20045 20046 20047 20048 20049 20050 20052 20053 20054 20055
 [1681] 20056 20057 20059 20060 20061 20062 20063 20064 20065 20066 20067 20068
 [1693] 20069 20070 20071 20072 20073 20074 20075 20076 20077 20078 20079 20081
 [1705] 20082 20083 20084 20085 20086 20087 20088 20089 20090 20091 20092 20093
 [1717] 20094 20095 20096 20097 20098 20099 20100 20101 20102 20103 20104 20105
 [1729] 20107 20108 20109 20110 20111 20112 20114 20115 20116 20117 20118 20120
 [1741] 20121 20122 20123 20124 20125 20126 20127 20129 20130 20131 20132 20133
 [1753] 20134 20135 20136 20137 20138 20139 20140 20141 20142 20143 20144 20145
 [1765] 20146 20147 20148 20149 20151 20152 20153 20154 20155 20157 20158 20159
 [1777] 20160 20161 20163 20164 20165 20167 20168 20169 20171 20172 20173 20174
 [1789] 20176 20177 20178 20179 20180 20181 20182 20183 20184 20185 20186 20187
 [1801] 20188 20189 20190 20192 20194 20195 20196 20197 20198 20199 20200 20201
 [1813] 20202 20203 20204 20205 20206 20207 20208 20209 20210 20211 20213 20214
 [1825] 20215 20216 20217 20218 20219 20220 20221 20222 20223 20224 20225 20226
 [1837] 20227 20229 20230 20232 20233 20234 20235 20238 20239 20240 20241 20242
 [1849] 20243 20244 20245 20246 20247 20248 20249 20250 20251 20252 20253 20254
 [1861] 20255 20256 20257 20258 20259 20260 20261 20262 20263 20264 20265 20266
 [1873] 20267 20268 20269 20270 20271 20272 20273 20276 20277 20278 20279 20280
 [1885] 20281 20282 20283 20284 20285 20286 20287 20288 20290 20291 20293 20294
 [1897] 20295 20297 20298 20299 20300 20301 20302 20303 20304 20305 20306 20307
 [1909] 20308 20309 20310 20311 20312 20313 20314 20315 20316 20317 20318 20319
 [1921] 20320 20321 20322 20323 20324 20325 20326 20327 20328 20329 20330 20332
 [1933] 20333 20334 20335 20336 20337 20338 20339 20340 20341 20342 20343 20344
 [1945] 20345 20346 20347 20349 20350 20351 20352 20353 20354 20355 20356 20357
 [1957] 20358 20359 20360 20361 20362 20363 20364 20365 20366 20367 20368 20369
 [1969] 20370 20371 20372 20373 20375 20376 20377 20378 20379 20380 20381 20382
 [1981] 20383 20384 20385 20386 20387 20388 20389 20390 20391 20393 20394 20395
 [1993] 20397 20398 20399 20400 20401 20402 20403 20404 20405 20406 20407 20408
 [2005] 20409 20410 20411 20412 20413 20414 20415 20417 20419 20420 20421 20422
 [2017] 20423 20424 20425 20426 20427 20428 20429 20430 20431 20432 20433 20435
 [2029] 20436 20438 20439 20440 20441 20442 20443 20444 20445 20446 20447 20448
 [2041] 20449 20450 20451 20452 20454 20455 20457 20458 20459 20460 20461 20462
 [2053] 20465 20466 20467 20468 20469 20470 20471 20473 20474 20475 20476 20477
 [2065] 20478 20479 20480 20481 20483 20485 20486 20487 20488 20489 20491 20492
 [2077] 20493 20494 20495 20496 20497 20499 20500 20501 20503 20504 20505 20506
 [2089] 20507 20509 20510 20511 20512 20513 20514 20515 20516 20519 20520 20521
 [2101] 20522 20523 20524 20525 20526 20527 20528 20529 20530 20531 20532 20533
 [2113] 20534 20535 20536 20537 20538 20539 20540 20542 20543 20544 20545 20548
 [2125] 20549 20550 20551 20552 20553 20555 20556 20557 20558 20559 20560 20561
 [2137] 20562 20563 20564 20565 20566 20567 20568 20569 20570 20571 20572 20573
 [2149] 20574 20575 20576 20577 20578 20579 20580 20581 20583 20584 20585 20587
 [2161] 20588 20589 20590 20591 20592 20593 20594 20595 20596 20597 20598 20599
 [2173] 20600 20601 20603 20604 20606 20607 20609 20610 20611 20613 20614 20615
 [2185] 20616 20617 20618 20619 20620 20621 20622 20623 20624 20625 20626 20627
 [2197] 20628 20629 20630 20631 20632 20633 20634 20635 20636 20637 20638 20639
 [2209] 20641 20642 20643 20645 20646 20647 20648 20649 20650 20652 20654 20655
 [2221] 20656 20658 20659 20660 20661 20662 20663 20664 20665 20666 20667 20668
 [2233] 20669 20672 20673 20674 20675 20676 20677 20678 20679 20680 20681 20682
 [2245] 20683 20684 20685 20686 20687 20688 20689 20690 20691 20692 20693 20694
 [2257] 20695 20696 20698 20700 20702 20704 20705 20706 20707 20708 20709 20710
 [2269] 20711 20713 20714 20715 20716 20717 20718 20719 20720 20721 20722 20723
 [2281] 20724 20725 20727 20728 20729 20730 20731 20733 20734 20735 20736 20738
 [2293] 20740 20741 20743 20744 20745 20746 20747 20748 20749 20750 20751 20752
 [2305] 20753 20754 20755 20756 20757 20758 20759 20760 20762 20763 20764 20765
 [2317] 20767 20770 20771 20772 20773 20774 20775 20776 20777 20778 20779 20780
 [2329] 20781 20782 20783 20784 20785 20786 20787 20788 20789 20791 20794 20795
 [2341] 20796 20799 20800 20801 20802 20804 20805 20808 20809 20810 20812 20813
 [2353] 20814 20816 20819 20820 20821 20823 20824 20825 20826 20827 20828 20829
 [2365] 20830 20832 20833 20834 20835 20837 20838 20839 20840 20841 20844 20845
 [2377] 20846 20847 20849 20850 20851 20852 20853 20854 20855 20856 20857 20858
 [2389] 20859 20860 20862 20863 20864 20865 20867 20868 20869 20870 20871 20872
 [2401] 20873 20874 20875 20876 20877 20878 20879 20881 20882 20883 20884 20886
 [2413] 20887 20888 20889 20890 20891 20892 20893 20894 20895 20897 20898 20899
 [2425] 20900 20902 20903 20904 20905 20906 20907 20908 20909 20910 20911 20912
 [2437] 20913 20914 20915 20916 20917 20918 20919 20920 20921 20922 20923 20924
 [2449] 20926 20927 20928 20929 20931 20933 20934 20936 20937 20938 20939 20940
 [2461] 20941 20943 20944 20945 20946 20947 20948 20949 20950 20951 20952 20953
 [2473] 20954 20956 20958 20959 20960 20961 20962 20963 20964 20965 20966 20967
 [2485] 20968 20969 20970 20971 20972 20973 20974 20975 20976 20977 20978 20979
 [2497] 20980 20981 20982 20983 20984 20985 20986 20987 20988 20990 20991 20992
 [2509] 20993 20994 20995 20996 20997 20998 20999 21000 21001 21002 21003 21004
 [2521] 21005 21006 21007 21008 21009 21010 21011 21012 21013 21014 21015 21016
 [2533] 21017 21018 21019 21020 21021 21022 21023 21024 21025 21027 21028 21029
 [2545] 21030 21031 21032 21034 21035 21037 21038 21039 21040 21041 21042 21043
 [2557] 21044 21045 21047 21048 21049 21050 21051 21052 21054 21055 21056 21057
 [2569] 21058 21059 21062 21063 21064 21065 21066 21067 21068 21069 21070 21071
 [2581] 21072 21073 21074 21075 21076 21077 21078 21079 21080 21081 21082 21083
 [2593] 21085 21086 21087 21088 21089 21090 21091 21092 21094 21096 21097 21098
 [2605] 21099 21100 21101 21102 21103 21104 21105 21106 21107 21108 21109 21110
 [2617] 21112 21113 21114 21115 21116 21118 21119 21120 21121 21122 21123 21125
 [2629] 21126 21127 21128 21129 21130 21131 21132 21133 21134 21135 21136 21137
 [2641] 21138 21140 21141 21142 21143 21145 21146 21147 21148 21149 21150 21151
 [2653] 21152 21153 21155 21156 21157 21158 21159 21160 21161 21162 21163 21164
 [2665] 21165 21166 21167 21168 21169 21171 21172 21173 21174 21175 21176 21177
 [2677] 21178 21179 21180 21181 21182 21183 21184 21185 21186 21187 21188 21189
 [2689] 21190 21191 21192 21193 21194 21195 21196 21197 21198 21200 21201 21202
 [2701] 21203 21204 21206 21207 21208 21209 21211 21212 21213 21214 21215 21217
 [2713] 21218 21219 21220 21221 21222 21223 21224 21225 21226 21227 21228 21229
 [2725] 21230 21231 21232 21233 21234 21235 21236 21237 21238 21239 21240 21241
 [2737] 21243 21244 21246 21248 21250 21251 21252 21253 21254 21255 21257 21258
 [2749] 21259 21260 21262 21263 21264 21265 21267 21268 21270 21271 21272 21273
 [2761] 21274 21275 21276 21277 21278 21279 21281 21282 21283 21284 21285 21286
 [2773] 21287 21288 21289 21291 21292 21294 21295 21296 21297 21298 21299 21300
 [2785] 21301 21302 21304 21305 21306 21307 21308 21310 21311 21312 21313 21314
 [2797] 21315 21316 21317 21319 21320 21321 21322 21323 21324 21325 21326 21327
 [2809] 21330 21331 21332 21333 21334 21335 21336 21337 21338 21339 21340 21341
 [2821] 21342 21344 21345 21346 21347 21348 21349 21350 21352 21353 21354 21355
 [2833] 21356 21357 21358 21359 21360 21361 21362 21363 21364 21366 21367 21368
 [2845] 21370 21371 21373 21374 21375 21376 21377 21379 21380 21381 21382 21383
 [2857] 21384 21385 21386 21387 21388 21389 21390 21392 21393 21394 21396 21397
 [2869] 21398 21399 21400 21401 21402 21403 21404 21405 21406 21407 21408 21409
 [2881] 21410 21411 21412 21413 21414 21415 21416 21417 21418 21419 21420 21421
 [2893] 21422 21423 21424 21425 21426 21427 21428 21429 21430 21431 21432 21433
 [2905] 21434 21435 21436 21437 21438 21439 21440 21441 21442 21443 21444 21445
 [2917] 21446 21447 21448 21449 21450 21451 21452 21453 21454 21455 21456 21457
 [2929] 21458 21459 21461 21462 21463 21464 21466 21467 21468 21469 21470 21471
 [2941] 21472 21473 21474 21475 21476 21477 21478 21479 21480 21482 21483 21484
 [2953] 21485 21486 21487 21488 21489 21490 21491 21492 21493 21494 21495 21496
 [2965] 21497 21498 21499 21500 21501 21502 21503 21504 21505 21506 21507 21509
 [2977] 21510 21511 21512 21513 21514 21515 21516 21517 21519 21520 21521 21522
 [2989] 21523 21525 21526 21527 21528 21529 21530 21531 21532 21533 21534 21535

titanic:

  [1]  4461  4473  4475  4482  4484  4485  4487  4488  4492  4498  4501  4502
 [13]  4503  4504  4511  4520  4521  4532  4533  4538  4543  4551  4557  4563
 [25]  4565  4577  4582  4584  4596  4610  4614  4615  4622  4624  4632  4636
 [37]  4637  4641  4642  4652  4654  4657  4670  4679  4685  4691  4696  4697
 [49]  4706  4712  4716  4720  4726  4730  4733  4740  4751  4754  4756  4757
 [61]  4759  4760  4762  4780  4786  4790  4791  4803  4807  4810  4814  4815
 [73]  4820  4823  4824  4831  4840  4844  4865  4866  4867  4869  4871  4876
 [85]  4881  4884  4887  4900  4907  4910  4913  4915  4920  4922  4924  4926
 [97]  4931  4937  4941  4946  4951  4953  4958  4963  4967  4973  4978  4980
[109]  4983  4987  4989  4994  5003  5008  5013  5016  5019  5020  5024  5029
[121]  5034  5040  5045  5049  5052  5054  5057  5058  5067  5068  5069  5085
[133]  5089  5095  5099  5104  5106  5109  5112  5123  5125  5130  5136  5148
[145]  5153  5165  5167  5174  5183  5188  5194  5195  5196  5216  5222  5224
[157]  5229  5232  5234  5239  5246  5248  5249  5271  5281  5282  5284  5288
[169]  5293  5295  5302  5305  5315  5319  5324  5334  5344  8911  8913  8915
[181]  8916  8918  8919  8920  8923  8924  8925  8926  8927  8928  8929  8930
[193]  8931  8933  8935  8936  8937  8939  8940  8941  8943  8944  8945  8946
[205]  8947  8948  8949  8950  8951  8952  8953  8954  8955  8956  8957  8958
[217]  8959  8960  8961  8962  8964  8967  8968  8969  8970  8971  8974  8975
[229]  8976  8978  8979  8980  8981  8982  8983  8984  8985  8987  8988  8989
[241]  8990  8991  8992  8993  8994  8995  8996  8997  8998  9000  9001  9002
[253]  9004  9005  9006  9009  9010  9011  9012  9014  9015  9016  9017  9018
[265]  9019  9020  9022  9023  9024  9025  9026  9027  9028  9030  9031  9032
[277]  9033  9036  9037  9038  9040  9041  9042  9043  9044  9045  9046  9049
[289]  9051  9052  9053  9054  9055  9056  9057  9058  9060  9061  9063  9064
[301]  9065  9066  9067  9068  9069  9070  9071  9072  9073  9074  9075  9076
[313]  9078  9079  9080  9082  9083  9084  9086  9087  9089  9090  9091  9092
[325]  9093  9095  9097  9098  9099  9100  9101  9102  9103  9107  9108  9109
[337]  9110  9111  9112  9113  9114  9115  9117  9118  9119  9121  9122  9123
[349]  9124  9125  9127  9128  9130  9131  9132  9133  9134  9136  9137  9138
[361]  9139  9140  9142  9143  9144  9145  9146  9147  9148  9149  9150  9151
[373]  9152  9153  9154  9155  9157  9158  9160  9161  9164  9165  9166  9167
[385]  9169  9170  9171  9172  9175  9176  9177  9178  9181  9182  9183  9185
[397]  9187  9188  9189  9190  9191  9192  9193  9194  9196  9197  9198  9199
[409]  9200  9201  9204  9205  9206  9207  9211  9212  9213  9215  9217  9219
[421]  9223  9224  9225  9226  9227  9228  9231  9232  9233  9234  9235  9237
[433]  9239  9241  9244  9245  9246  9249  9253  9254  9255  9257  9258  9259
[445]  9260  9261  9263  9264  9265  9266  9268  9269  9270  9271  9272  9273
[457]  9274  9275  9276  9278  9279  9282  9283  9284  9285  9286  9287  9289
[469]  9290  9291  9292  9293  9294  9295  9296  9297  9298  9299  9300  9302
[481]  9303  9306  9307  9308  9309  9310  9311  9312  9313  9314  9315  9316
[493]  9317  9318  9319  9320  9321  9322  9324  9325  9326  9327  9328  9329
[505]  9330  9331  9332  9333  9334  9335  9336  9337  9338  9339  9342  9343
[517]  9344  9347  9348  9350  9351  9352  9353  9354  9355  9357  9358  9359
[529]  9361  9362  9365  9366  9369  9370  9372  9374  9375  9376  9377  9378
[541]  9379  9380  9381  9382  9383  9385  9387  9388  9389  9390  9391  9392
[553]  9393  9394  9396  9399  9400  9401  9402  9404  9405  9406  9408  9410
[565]  9411  9412  9413  9414  9417  9418  9419  9420  9421  9422  9424  9425
[577]  9428  9429  9430  9432  9433  9435  9436  9437  9439  9440  9441  9442
[589]  9443  9444  9445  9446  9448  9449  9452  9453  9454  9456  9457  9458
[601]  9459  9460  9462  9463  9464  9465  9466  9468  9470  9471  9472  9473
[613]  9474  9475  9476  9477  9478  9479  9480  9481  9484  9485  9486  9487
[625]  9489  9490  9491  9493  9495  9497  9499  9500  9501  9503  9504  9505
[637]  9506  9507  9508  9509  9511  9512  9513  9514  9515  9516  9517  9518
[649]  9519  9521  9522  9523  9524  9525  9526  9527  9528  9530  9531  9533
[661]  9534  9535  9537  9539  9540  9542  9544  9545  9546  9547  9548  9549
[673]  9550  9551  9553  9554  9555  9557  9559  9560  9561  9562  9563  9564
[685]  9565  9566  9567  9568  9569  9571  9572  9574  9575  9576  9577  9578
[697]  9579  9581  9583  9584  9585  9586  9587  9588  9589  9591  9593  9594
[709]  9595  9596  9597  9598  9599  9602  9603  9604  9605  9606  9607  9608
[721]  9613  9614  9615  9616  9617  9619  9620  9624  9625  9629  9630  9631
[733]  9632  9633  9634  9636  9637  9638  9639  9640  9642  9643  9644  9645
[745]  9646  9647  9649  9650  9654  9655  9657  9658  9660  9661  9663  9664
[757]  9665  9666  9667  9668  9669  9671  9672  9673  9675  9677  9678  9679
[769]  9680  9681  9682  9684  9685  9686  9688  9689  9691  9694  9695  9696
[781]  9697  9698  9699  9701  9702  9703  9704  9705  9706  9708  9709  9710
[793]  9711  9712  9714  9715  9716  9718  9719  9721  9722  9723  9724  9725
[805]  9727  9728  9729  9730  9732  9733  9735  9736  9737  9738  9739  9741
[817]  9742  9743  9744  9745  9747  9748  9749  9751  9752  9753  9754  9755
[829]  9756  9757  9758  9759  9761  9762  9763  9765  9766  9767  9769  9770
[841]  9771  9772  9774  9775  9776  9777  9779  9780  9781  9784  9785  9786
[853]  9787  9788  9789  9791  9792  9793  9794  9795  9796  9797  9799  9801
[865]  9863 10631

[1] 2

[1] 3 5

             City Colors.Reported  Shape.Reported           State            Time
             25           15359            2644               0               0
  PassengerId    Survived      Pclass        Name         Sex         Age
          0           0           0           0           0         177
      SibSp       Parch      Ticket        Fare       Cabin    Embarked
          0           0           0           0         687           2

In [16]:
dim(uforeport)
uforeport_cleaned = na.omit(uforeport)
dim(uforeport_cleaned)
dim(titanic)
titanic_cleaned = na.omit(titanic)
dim(titanic_cleaned)

[1] 18241     5

[1] 2486    5

[1] 891  12

[1] 183  12

In [42]:
library(readr)
library(dplyr)
library(lubridate)
# 1. Count by City
city_counts <- uforeport %>%count(City, sort = TRUE)

print("Top 3 Cities:")
head(city_counts, 3)

colour_count <- uforeport %>%count( Colors.Reported ,sort=TRUE)%>%
  filter(!is.na(Colors.Reported))
print("Top 3 colours:")
head(colour_count,3)

colour_count <- uforeport %>%count( Shape.Reported ,sort=TRUE)%>%
  filter(!is.na(Shape.Reported))
print("Top 3 Shape:")
head( colour_count,3)

state_counts <- uforeport %>%count(State, sort = TRUE)

print("Top 3 States:")
head(state_counts, 3)

ufo_with_year <- uforeport %>%mutate(DateTime = mdy_hm(Time),
         Year = year(DateTime))

year_counts <- ufo_with_year %>%count(Year, sort = TRUE)

print("Top 3 Years with most sightings:")
head(year_counts, 3)

[1] "Top 3 Cities:"

  City          n
1 Seattle       187
2 New York City 161
3 Phoenix       137

[1] "Top 3 colours:"

  Colors.Reported n
1 RED             780
2 GREEN           531
3 ORANGE          528

[1] "Top 3 Shape:"

  Shape.Reported n
1 LIGHT          2803
2 DISK           2122
3 TRIANGLE       1889

[1] "Top 3 States:"

  State n
1 CA    2529
2 WA    1322
3 TX    1027

[1] "Top 3 Years with most sightings:"

  Year n
1 1999 2774
2 2000 2635
3 1998 1743

In [45]:
top_state_name <- uforeport %>%
  count(State, sort = TRUE) %>%
  slice(1) %>%
  pull(State)

# 3. Create a list of the categories you want to analyze for that State
categories <- c("City", "Shape.Reported", "Colors.Reported")

# 4. Use lapply to run the same logic across all categories at once
# This excludes NAs automatically for each category
top_state_stats <- lapply(categories, function(cat) {
  uforeport %>%
    filter(State == top_state_name) %>% # Look only at the top state
    filter(!is.na(!!sym(cat))) %>%      # Remove missing values
    count(!!sym(cat), sort = TRUE) %>%  # Count and sort
    head(1)                             # Keep only the #1 result
})

# Assign names to the list for easy reading
names(top_state_stats) <- categories

# --- FINAL OUTPUT ---
cat("--- Analysis for Top State:", top_state_name, "---\n")
print(top_state_stats)

--- Analysis for Top State: CA ---
$City
       City   n
1 San Diego 101

$Shape.Reported
  Shape.Reported   n
1          LIGHT 394

$Colors.Reported
  Colors.Reported   n
1             RED 117

In [49]:
library(readr)
library(dplyr)
library(tidyr)

# 1. Load the data
titanic_df <- read_csv("titanic.csv")

# 2. Create a function to calculate survival rates and percentages
# This avoids repetitive code for Sex, Pclass, and Embarked
get_survival_stats <- function(df, column_name) {
  df %>%
    filter(!is.na(!!sym(column_name))) %>%      # Exclude NAs
    group_by(!!sym(column_name)) %>%
    summarise(
      Total_Passengers = n(),
      Survived_Count = sum(Survived == 1),
      Survival_Rate = (Survived_Count / Total_Passengers) * 100
    ) %>%
    arrange(desc(Survival_Rate))
}

# 3. Apply the function to main categories
categories <- c("Sex", "Pclass", "Embarked")
titanic_results <- lapply(categories, function(cat) get_survival_stats(titanic_df, cat))
names(titanic_results) <- categories

# 4. Specific Insight: Pclass distribution for survivors from Cherbourg (C)
cherbourg_survivors_class <- titanic_df %>%
  filter(Embarked == "C", Survived == 1) %>%
  count(Pclass) %>%
  mutate(Percentage = (n / sum(n)) * 100)

# --- PRINT RESULTS ---
print("--- Survival Statistics by Category ---")
print(titanic_results)

print("--- Class Distribution of Survivors from Cherbourg ---")
print(cherbourg_survivors_class)

Rows: 891 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Name, Sex, Ticket, Cabin, Embarked
dbl (7): PassengerId, Survived, Pclass, Age, SibSp, Parch, Fare

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "--- Survival Statistics by Category ---"
$Sex
# A tibble: 2 × 4
  Sex    Total_Passengers Survived_Count Survival_Rate
  <chr>             <int>          <int>         <dbl>
1 female              314            233          74.2
2 male                577            109          18.9

$Pclass
# A tibble: 3 × 4
  Pclass Total_Passengers Survived_Count Survival_Rate
   <dbl>            <int>          <int>         <dbl>
1      1              216            136          63.0
2      2              184             87          47.3
3      3              491            119          24.2

$Embarked
# A tibble: 3 × 4
  Embarked Total_Passengers Survived_Count Survival_Rate
  <chr>               <int>          <int>         <dbl>
1 C                     168             93          55.4
2 Q                      77             30          39.0
3 S                     644            217          33.7

[1] "--- Class Distribution of Survivors from Cherbourg ---"
# A tibble: 3 × 3
  Pclass     n Percentage
   <dbl> <int>      <dbl>
1      1    59      63.4
2      2     9       9.68
3      3    25      26.9